version: "3.9"

services:

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: alhammi
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: sonar
    networks: 
      - jenkins
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  SonarQube:
    image: sonarqube:lts-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: alhammi
      SONAR_JDBC_PASSWORD: abc123
    volumes:
      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
    ports:
      - "9010:9010"
    networks: 
      - jenkins

  jenkins-docker:
    image: "jenkins-docker"
    build: .
    ports: 
      - "8082:8080"
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

  pg-admin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - jenkins

volumes:
  jenkins_home:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  postgresql:
  postgresql_data:
  pgadmin-data:

networks:
  jenkins:
    